# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import acl_pb2 as acl__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in acl_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentRegistryServiceStub(object):
    """─── gRPC Service Definitions ───────────────────────────────────

    Agent Registry Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterAgent = channel.unary_unary(
                '/acl.v1.AgentRegistryService/RegisterAgent',
                request_serializer=acl__pb2.AgentCapability.SerializeToString,
                response_deserializer=acl__pb2.RegisterResponse.FromString,
                _registered_method=True)
        self.DeregisterAgent = channel.unary_unary(
                '/acl.v1.AgentRegistryService/DeregisterAgent',
                request_serializer=acl__pb2.DeregisterRequest.SerializeToString,
                response_deserializer=acl__pb2.DeregisterResponse.FromString,
                _registered_method=True)
        self.FindAgents = channel.unary_unary(
                '/acl.v1.AgentRegistryService/FindAgents',
                request_serializer=acl__pb2.AgentQuery.SerializeToString,
                response_deserializer=acl__pb2.QueryResponse.FromString,
                _registered_method=True)
        self.ListAgents = channel.unary_unary(
                '/acl.v1.AgentRegistryService/ListAgents',
                request_serializer=acl__pb2.ListAgentsRequest.SerializeToString,
                response_deserializer=acl__pb2.QueryResponse.FromString,
                _registered_method=True)


class AgentRegistryServiceServicer(object):
    """─── gRPC Service Definitions ───────────────────────────────────

    Agent Registry Service
    """

    def RegisterAgent(self, request, context):
        """Register a new agent with capabilities
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeregisterAgent(self, request, context):
        """Deregister an agent
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindAgents(self, request, context):
        """Find agents by capability
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAgents(self, request, context):
        """List all registered agents
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentRegistryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterAgent,
                    request_deserializer=acl__pb2.AgentCapability.FromString,
                    response_serializer=acl__pb2.RegisterResponse.SerializeToString,
            ),
            'DeregisterAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.DeregisterAgent,
                    request_deserializer=acl__pb2.DeregisterRequest.FromString,
                    response_serializer=acl__pb2.DeregisterResponse.SerializeToString,
            ),
            'FindAgents': grpc.unary_unary_rpc_method_handler(
                    servicer.FindAgents,
                    request_deserializer=acl__pb2.AgentQuery.FromString,
                    response_serializer=acl__pb2.QueryResponse.SerializeToString,
            ),
            'ListAgents': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAgents,
                    request_deserializer=acl__pb2.ListAgentsRequest.FromString,
                    response_serializer=acl__pb2.QueryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'acl.v1.AgentRegistryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('acl.v1.AgentRegistryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentRegistryService(object):
    """─── gRPC Service Definitions ───────────────────────────────────

    Agent Registry Service
    """

    @staticmethod
    def RegisterAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/acl.v1.AgentRegistryService/RegisterAgent',
            acl__pb2.AgentCapability.SerializeToString,
            acl__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeregisterAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/acl.v1.AgentRegistryService/DeregisterAgent',
            acl__pb2.DeregisterRequest.SerializeToString,
            acl__pb2.DeregisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FindAgents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/acl.v1.AgentRegistryService/FindAgents',
            acl__pb2.AgentQuery.SerializeToString,
            acl__pb2.QueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAgents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/acl.v1.AgentRegistryService/ListAgents',
            acl__pb2.ListAgentsRequest.SerializeToString,
            acl__pb2.QueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class TaskServiceStub(object):
    """Task Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitTask = channel.unary_unary(
                '/acl.v1.TaskService/SubmitTask',
                request_serializer=acl__pb2.ActionPacket.SerializeToString,
                response_deserializer=acl__pb2.TaskResponse.FromString,
                _registered_method=True)
        self.ClaimTask = channel.unary_unary(
                '/acl.v1.TaskService/ClaimTask',
                request_serializer=acl__pb2.ClaimRequest.SerializeToString,
                response_deserializer=acl__pb2.TaskResponse.FromString,
                _registered_method=True)
        self.UpdateTaskState = channel.unary_unary(
                '/acl.v1.TaskService/UpdateTaskState',
                request_serializer=acl__pb2.StateUpdate.SerializeToString,
                response_deserializer=acl__pb2.TaskResponse.FromString,
                _registered_method=True)
        self.QueryTasks = channel.unary_unary(
                '/acl.v1.TaskService/QueryTasks',
                request_serializer=acl__pb2.TaskQuery.SerializeToString,
                response_deserializer=acl__pb2.QueryResponse.FromString,
                _registered_method=True)
        self.GetTask = channel.unary_unary(
                '/acl.v1.TaskService/GetTask',
                request_serializer=acl__pb2.GetTaskRequest.SerializeToString,
                response_deserializer=acl__pb2.TaskNode.FromString,
                _registered_method=True)
        self.SubscribeEvents = channel.unary_stream(
                '/acl.v1.TaskService/SubscribeEvents',
                request_serializer=acl__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=acl__pb2.Event.FromString,
                _registered_method=True)


class TaskServiceServicer(object):
    """Task Service
    """

    def SubmitTask(self, request, context):
        """Submit a new task (creates ActionPacket -> TaskNode)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClaimTask(self, request, context):
        """Claim a pending task
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateTaskState(self, request, context):
        """Update task state
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryTasks(self, request, context):
        """Query tasks
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTask(self, request, context):
        """Get task by ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeEvents(self, request, context):
        """Subscribe to task events (server-side streaming)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TaskServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitTask': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitTask,
                    request_deserializer=acl__pb2.ActionPacket.FromString,
                    response_serializer=acl__pb2.TaskResponse.SerializeToString,
            ),
            'ClaimTask': grpc.unary_unary_rpc_method_handler(
                    servicer.ClaimTask,
                    request_deserializer=acl__pb2.ClaimRequest.FromString,
                    response_serializer=acl__pb2.TaskResponse.SerializeToString,
            ),
            'UpdateTaskState': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateTaskState,
                    request_deserializer=acl__pb2.StateUpdate.FromString,
                    response_serializer=acl__pb2.TaskResponse.SerializeToString,
            ),
            'QueryTasks': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryTasks,
                    request_deserializer=acl__pb2.TaskQuery.FromString,
                    response_serializer=acl__pb2.QueryResponse.SerializeToString,
            ),
            'GetTask': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTask,
                    request_deserializer=acl__pb2.GetTaskRequest.FromString,
                    response_serializer=acl__pb2.TaskNode.SerializeToString,
            ),
            'SubscribeEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeEvents,
                    request_deserializer=acl__pb2.SubscribeRequest.FromString,
                    response_serializer=acl__pb2.Event.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'acl.v1.TaskService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('acl.v1.TaskService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TaskService(object):
    """Task Service
    """

    @staticmethod
    def SubmitTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/acl.v1.TaskService/SubmitTask',
            acl__pb2.ActionPacket.SerializeToString,
            acl__pb2.TaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClaimTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/acl.v1.TaskService/ClaimTask',
            acl__pb2.ClaimRequest.SerializeToString,
            acl__pb2.TaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateTaskState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/acl.v1.TaskService/UpdateTaskState',
            acl__pb2.StateUpdate.SerializeToString,
            acl__pb2.TaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryTasks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/acl.v1.TaskService/QueryTasks',
            acl__pb2.TaskQuery.SerializeToString,
            acl__pb2.QueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/acl.v1.TaskService/GetTask',
            acl__pb2.GetTaskRequest.SerializeToString,
            acl__pb2.TaskNode.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/acl.v1.TaskService/SubscribeEvents',
            acl__pb2.SubscribeRequest.SerializeToString,
            acl__pb2.Event.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SpawnServiceStub(object):
    """Spawn Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Spawn = channel.unary_unary(
                '/acl.v1.SpawnService/Spawn',
                request_serializer=acl__pb2.SpawnRequest.SerializeToString,
                response_deserializer=acl__pb2.SpawnResponse.FromString,
                _registered_method=True)
        self.Terminate = channel.unary_unary(
                '/acl.v1.SpawnService/Terminate',
                request_serializer=acl__pb2.TerminateRequest.SerializeToString,
                response_deserializer=acl__pb2.TerminateResponse.FromString,
                _registered_method=True)
        self.GetSpawnTree = channel.unary_unary(
                '/acl.v1.SpawnService/GetSpawnTree',
                request_serializer=acl__pb2.GetSpawnTreeRequest.SerializeToString,
                response_deserializer=acl__pb2.SpawnTree.FromString,
                _registered_method=True)


class SpawnServiceServicer(object):
    """Spawn Service
    """

    def Spawn(self, request, context):
        """Request to spawn a new subagent
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Terminate(self, request, context):
        """Terminate a subagent
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSpawnTree(self, request, context):
        """Get spawn tree for an agent
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SpawnServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Spawn': grpc.unary_unary_rpc_method_handler(
                    servicer.Spawn,
                    request_deserializer=acl__pb2.SpawnRequest.FromString,
                    response_serializer=acl__pb2.SpawnResponse.SerializeToString,
            ),
            'Terminate': grpc.unary_unary_rpc_method_handler(
                    servicer.Terminate,
                    request_deserializer=acl__pb2.TerminateRequest.FromString,
                    response_serializer=acl__pb2.TerminateResponse.SerializeToString,
            ),
            'GetSpawnTree': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSpawnTree,
                    request_deserializer=acl__pb2.GetSpawnTreeRequest.FromString,
                    response_serializer=acl__pb2.SpawnTree.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'acl.v1.SpawnService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('acl.v1.SpawnService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SpawnService(object):
    """Spawn Service
    """

    @staticmethod
    def Spawn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/acl.v1.SpawnService/Spawn',
            acl__pb2.SpawnRequest.SerializeToString,
            acl__pb2.SpawnResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Terminate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/acl.v1.SpawnService/Terminate',
            acl__pb2.TerminateRequest.SerializeToString,
            acl__pb2.TerminateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSpawnTree(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/acl.v1.SpawnService/GetSpawnTree',
            acl__pb2.GetSpawnTreeRequest.SerializeToString,
            acl__pb2.SpawnTree.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ArtifactServiceStub(object):
    """Artifact Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PublishArtifact = channel.unary_unary(
                '/acl.v1.ArtifactService/PublishArtifact',
                request_serializer=acl__pb2.Artifact.SerializeToString,
                response_deserializer=acl__pb2.ArtifactReference.FromString,
                _registered_method=True)
        self.GetArtifact = channel.unary_unary(
                '/acl.v1.ArtifactService/GetArtifact',
                request_serializer=acl__pb2.ArtifactReference.SerializeToString,
                response_deserializer=acl__pb2.Artifact.FromString,
                _registered_method=True)
        self.QueryArtifacts = channel.unary_unary(
                '/acl.v1.ArtifactService/QueryArtifacts',
                request_serializer=acl__pb2.ArtifactQuery.SerializeToString,
                response_deserializer=acl__pb2.QueryResponse.FromString,
                _registered_method=True)


class ArtifactServiceServicer(object):
    """Artifact Service
    """

    def PublishArtifact(self, request, context):
        """Publish an artifact
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetArtifact(self, request, context):
        """Retrieve an artifact
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryArtifacts(self, request, context):
        """Query artifacts
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ArtifactServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PublishArtifact': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishArtifact,
                    request_deserializer=acl__pb2.Artifact.FromString,
                    response_serializer=acl__pb2.ArtifactReference.SerializeToString,
            ),
            'GetArtifact': grpc.unary_unary_rpc_method_handler(
                    servicer.GetArtifact,
                    request_deserializer=acl__pb2.ArtifactReference.FromString,
                    response_serializer=acl__pb2.Artifact.SerializeToString,
            ),
            'QueryArtifacts': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryArtifacts,
                    request_deserializer=acl__pb2.ArtifactQuery.FromString,
                    response_serializer=acl__pb2.QueryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'acl.v1.ArtifactService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('acl.v1.ArtifactService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ArtifactService(object):
    """Artifact Service
    """

    @staticmethod
    def PublishArtifact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/acl.v1.ArtifactService/PublishArtifact',
            acl__pb2.Artifact.SerializeToString,
            acl__pb2.ArtifactReference.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetArtifact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/acl.v1.ArtifactService/GetArtifact',
            acl__pb2.ArtifactReference.SerializeToString,
            acl__pb2.Artifact.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryArtifacts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/acl.v1.ArtifactService/QueryArtifacts',
            acl__pb2.ArtifactQuery.SerializeToString,
            acl__pb2.QueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
